### PR TITLE
[14.0][MIG] fleet_vehicle_service_calendar: Migration to 14.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Depends #35

### CODE REVIEW

**Comment by mamcode** [comment]
@marcelsavegnago Do you have any problems to end this migration?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago Do you have any problems to end this migration?

Yes ... I had problems with the cost_subtype_id field and I still haven't been able to concentrate on this case. If you want to help and can present a PR for my fork, I’ll give you the merge.

https://travis-ci.com/github/OCA/fleet/jobs/492923164#L957

**Comment by mamcode** [comment]
> > @marcelsavegnago Do you have any problems to end this migration?
> 
> Yes ... I had problems with the cost_subtype_id field and I still haven't been able to concentrate on this case. If you want to help and can present a PR for my fork, I’ll give you the merge.
> 
> https://travis-ci.com/github/OCA/fleet/jobs/492923164#L957

Ok this week I look at it :+1:

**Comment by mamcode** [comment]
Hello @marcelsavegnago I have sent PR to your fork.

**Comment by mamcode** [comment]
Hello @marcelsavegnago I have sent PR to your fork to fix the pre-commit issue.

**Comment by mamcode** [comment]
@marcelsavegnago @ivantodorovich Please review here.

**Review by ivantodorovich — APPROVED** [review]
Lgtm

Please rebase to get the green build 😊

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago @ivantodorovich Please review here.

LGTM.. Thanks

**Comment by ivantodorovich** [comment]
Do you think you can improve coverage to reach the target and get all green?

**Pull request merged**
