### PR TITLE
[12][ADD] new module fleet_vehicle_category

### PR DESCRIPTION
**Pull request by mymage**
This module add the possibility to assign a category to a vehicle.
This category can be used to manage vehicles that have the same functionality, regardless model or producer.

### CODE REVIEW

**Comment by mymage** [comment]
@ivantodorovich This is the substitute of #5

**Review by ivantodorovich — APPROVED** [review]

**Review by mamcode — APPROVED** [review]
Looks good to me, but the `Tags` field cannot serve this same purpose ?

**Comment by ivantodorovich** [comment]
Thanks @mymage !!

We'd really appreciate your help reviewing some of these :)

 https://github.com/OCA/fleet/pull/1 https://github.com/OCA/fleet/pull/2 https://github.com/OCA/fleet/pull/3 https://github.com/OCA/fleet/pull/4

**Comment by mymage** [comment]
@mamcode 
> Looks good to me, but the `Tags` field cannot serve this same purpose ?

It can be, but my way to structure db is to create a field for each "caracteristic" of the object. For me tags are useful when you assign an information that will not be structured but free because it may vary or expand in time.
Thanks for suggestion anyway.

**Comment by mamcode** [comment]
@mymage 
> It can be, but my way to structure db is to create a field for each "caracteristic" of the object. For me tags are useful when you assign an information that will not be structured but free because it may vary or expand in time.
> Thanks for suggestion anyway.

In that case you're right, thanks for your contribution.

**Pull request merged**
