### PR TITLE
[15.0] [MIG] fleet_vehicle_service_services: Migration to 15.0

### PR DESCRIPTION
**Pull request by rodrigonevest**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by marcelsavegnago — CHANGES_REQUESTED** [review]
@rodrigonevest please, delete migrations folder.

**Comment by rodrigonevest** [comment]
> @rodrigonevest please, delete migrations folder.

@marcelsavegnago the folder has been deleted.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
