### PR TITLE
[12.0][ADD] fleet_vehicle_calendar_year

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
Code LGTM :+1: 

Can you explain maybe in the readme what's the purpose of the calendar_year field, as opposed to the core model_year ?

**Comment by marcelsavegnago** [comment]
> Code LGTM 👍
> 
> Can you explain maybe in the readme what's the purpose of the calendar_year field, as opposed to the core model_year ?

@ivantodorovich done

**Comment by marcelsavegnago** [comment]
ping @mamcode @mymage

**Review by mymage — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
