### PR TITLE
[MIG] fleet_vehicle_log_fuel: Migration to 16.0

### PR DESCRIPTION
**Pull request by AnizR**
migration of fleet_vehicle_log_fuel from 14.0 to 16.0:

- some modification due to pre-commit
- major modification of 'fleet.vehicle.cost.report' : add fuel in 'cost_type' and modify init() query to have fuel 'cost_type'

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @rodrigonevest

**Comment by ivantodorovich** [comment]
It's a bit difficult to review for me as I'm not familiar with this module, there's a lot of sql and no unit tests, unfortunately.
I'll let the module authors and contributors take care of this ;)

**Comment by rodrigonevest** [comment]
@AnizR, could you implement more tests?

**Comment by rodrigonevest** [comment]
@AnizR can you add tests please?

**Comment by AnizR** [comment]
> @AnizR, could you implement more tests?

Yes, I will

**Comment by AnizR** [comment]
> > @AnizR, could you implement more tests?
> 
> Yes, I will

Finally, I won't  use this module so, I won't invest any more time in it. 

If anyone want to re-use this PR, your are free to do it!
In the meantime, I close this PR.

**Pull request closed without merging**
