### PR TITLE
[14.0][MIG] fleet_vehicle_license_plate_alt: Migration to 14.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@mamcode I had a problem with this migration as well. If you can take a look I appreciate it.
https://travis-ci.com/github/OCA/fleet/jobs/491927919#L974

cc @mymage

**Comment by mamcode** [comment]
> @mamcode I had a problem with this migration as well. If you can take a look I appreciate it.
> https://travis-ci.com/github/OCA/fleet/jobs/491927919#L974
> 
> cc @mymage

I'm sorry I can hardly see this comment, in the next few days I will review that issue you are commenting on.

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich @mamcode

**Review by mamcode — APPROVED** [review]
Thanks for this migration @marcelsavegnago 
Sorry for the delay 👍🏼

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Thanks!!

/ocabot merge nobump

**Pull request merged**
