### PR TITLE
[MIG][12.0] fleet vehicle history date end

### PR DESCRIPTION
**Pull request by mymage**
Backportig from 13.0

### CODE REVIEW

**Comment by mymage** [comment]
@ivantodorovich ready to check, thanks.

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
fast tracking this

/ocabot merge nobump

**Comment by mamcode** [comment]
@ivantodorovich The unit tests of fleet_vehicle_history_date_end were not executed.I have confirmed it in travis logs and in my local instance, do you know why this happens ?

**Comment by mamcode** [comment]
@ivantodorovich It is because the test class has the decorator `@tagged('-standard')`, for execute the unit tests the instance must be run with `--test-tags=fleet_vehicle_history_date_end`.
I have noticed that the unit tests for version 12.0 are not passing, I think it should be revised by @mymage .

**Pull request merged**
