### PR TITLE
[12.0][IMP] fleet vehicle inspection: improvements from 14.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@mymage if you can review this PR I thank you

**Comment by marcelsavegnago** [comment]
ping @rvalyi @ivantodorovich

**Review by mymage — APPROVED** [review]
LGTM
Only two points:
- testing with bot online I can't see the images preview
- adding document like a PDF can be a good option (but probabily it is alredy available an I don't know)

**Comment by marcelsavegnago** [comment]
> LGTM
> Only two points:
> 
> * testing with bot online I can't see the images preview
> * adding document like a PDF can be a good option (but probabily it is alredy available an I don't know)

I saw, after the image is recorded, the preview of the images in the kanban view is not displayed. It is visible only after recording the inspection but I already have it on the roadmap to look for a solution.

The pdf report is also on the roadmap.

**Comment by marcelsavegnago** [comment]
@ivantodorovich These improvements came from version 14.0 can you review and merge please?

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
Thanks @marcelsavegnago !

When backporting features, please keep consistent commit messages (ideally the same commit messages than the ones in the backported version). Here "Improvements from 14.0" isn't very clear

Also it seems code formatting got in the way, making it harder for reviewers to identify the changes. Take for example the diff on `__manifest__.py`, where you have 46 lines changed. In case code re-formatting is needed, like for pre-commit, please do it in a separate commit.

**Comment by marcelsavegnago** [comment]
> Thanks @marcelsavegnago !
> 
> When backporting features, please keep consistent commit messages (ideally the same commit messages than the ones in the backported version). Here "Improvements from 14.0" isn't very clear
> 
> Also it seems code formatting got in the way, making it harder for reviewers to identify the changes. Take for example the diff on `__manifest__.py`, where you have 46 lines changed. In case code re-formatting is needed, like for pre-commit, please do it in a separate commit.

Yes you are right. I will separate the commits.

About the changes in the files like __manifest__.py I thought it would give a headache .. I will fix it.

**Comment by ivantodorovich** [comment]
> Yes you are right. I will separate the commits.

:+1: great ! thanks!

> About the changes in the files like **manifest**.py I thought it would give a headache .. I will fix it.

Yeah! keep in mind the __manifest__.py was just an example. These code-style format changs are in pretty much all files :sweat_smile:

**Comment by marcelsavegnago** [comment]
@ivantodorovich done.

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Thanks @marcelsavegnago ! :tada: 

/ocabot merge major

**Pull request merged**
