### PR TITLE
[17.0][MIG] fleet_vehicle_usage: Migration to 17.0

### PR DESCRIPTION
**Pull request by elheit**

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hello!

Thanks for the contribution!

Could you please check the commit history on this PR, it doesn't look right.
There are commits/changes involving other modules than `fleet_vehicle_usage`

**Comment by elheit** [comment]
Hello,
at first i want to migrate just the fleet_vehicle_usage module after that i see the issue target modules list so i want to migrate them all
so should create a request for each module or just rename this request

**Comment by marcelsavegnago** [comment]
@elheit 

Take a look https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

One module per PR please.

**Review by marcelsavegnago — CHANGES_REQUESTED** [review]
One module per PR, please.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by elheit** [comment]
now it is just one module

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by elheit** [comment]
Hello,
Yes I have done it this way

**Comment by pedrobaeza** [comment]
I'm afraid not. You haven't respected the previous commit history of the previous contributors of the module. Read my previous message.

**Comment by elheit** [comment]
i have check again and the commit history is from the last commit in the branch 17.0 
can you explain to me in more detail what exectly the problem

**Comment by pedrobaeza** [comment]
You haven't preserved all the commit history, which is https://github.com/OCA/fleet/commits/16.0/fleet_vehicle_usage

**Comment by victoralmau** [comment]
Superseded by https://github.com/OCA/fleet/pull/166

**Pull request closed without merging**
