### PR TITLE
[14.0][ADD] fleet_vehicle_inspection_item_product

### PR DESCRIPTION
**Pull request by marcelsavegnago**
depends #43 
depends #44

### CODE REVIEW

**Comment by mymage** [comment]
If I understand, with this module you can manage veichle items as product so you can for example have an inventori quantity,
LGTM and waiting to do a test.

**Comment by marcelsavegnago** [comment]
> If I understand, with this module you can manage veichle items as product so you can for example have an inventori quantity,
> LGTM and waiting to do a test.

Creating this relationship between product and inspection item, the idea is during the inspection to create a kind of repair budget in which it will be possible to select only products compatible with the vehicle model and with the inspected item. In this case, a filter would be applied to show only products compatible with the vehicle model and with the item inspected and which failed. But we can also extend it at another time for inventory management as well.

**Comment by marcelsavegnago** [comment]
I tried to sketch the idea in this diagram :) ..

image

note: In inspection items the idea is to allow linking any product regardless of the vehicle model.

**Comment by mymage** [comment]
Thanks for clarification.
Are you sure to free the link between product and veichle model? This mean that it is possible to use a part not compatible, if I understand.

**Comment by marcelsavegnago** [comment]
> Thanks for clarification.
> Are you sure to free the link between product and veichle model? This mean that it is possible to use a part not compatible, if I understand.

I understand your question ... I will give a better thought in these modules.

**Comment by marcelsavegnago** [comment]
New PR https://github.com/OCA/fleet/pull/61

**Pull request closed without merging**
