### PR TITLE
[ADD] fleet_vehicle_purchase

### PR DESCRIPTION
**Pull request by etobella**
Allow to define fleet vehicles on Purchase Orders in order to inherit them properly

### CODE REVIEW

**Comment by rpsjr** [comment]
runboat functional test fails, trying to associate a veichle to a purchase order

image
image


Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 400, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 373, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1805, in name_search
    return self.browse(ids).sudo().name_get()
  File "/opt/odoo/odoo/models.py", line 1750, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/opt/odoo/odoo/models.py", line 5716, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 1019, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/odoo/models.py", line 3078, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/odoo/models.py", line 3145, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-5>", line 2, in execute
  File "/opt/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
  File "/opt/odoo-venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 126, in getquoted
    qobjs = [o.getquoted() for o in pobjs]
  File "/opt/odoo-venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 126, in <listcomp>
    qobjs = [o.getquoted() for o in pobjs]
  File "/opt/odoo-venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 121, in getquoted
    pobjs = [adapt(o) for o in self._seq]
  File "/opt/odoo-venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 121, in <listcomp>
    pobjs = [adapt(o) for o in self._seq]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: can't adapt type 'lazy'

**Comment by etobella** [comment]
I see the issue, but it is unrelated to this module. Obviously, If you go to services and try to change the vehicle, the same error is raised.  Anyway, I will check why this happens

**Comment by rpsjr** [comment]
> I see the issue, but it is unrelated to this module. Obviously, If you go to services and try to change the vehicle, the same error is raised. Anyway, I will check why this happens

the patch solved the error, could u rebase?

and, what do u think about add vehicle field to the purchase PDF reports?

**Review by ivantodorovich — APPROVED** [review]
LGTM, thanks! :)

**Comment by marcelsavegnago** [comment]
@etobella Can you do a rebase, please?

**Review by marcelsavegnago — APPROVED** [review]
LGTM. :heart:

**Pull request merged**
