### PR TITLE
[12.0][ADD] base_fleet module

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @mancode @mymage @rvalyi @ivantodorovich

**Review by mymage — APPROVED** [review]

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
Hello @marcelsavegnago !

I don't think these features should be in a `base_` module, as the real "base" here is the core `fleet` module.

You should probably isolate these features into separate modules, each implementing one or some of them. You can check, for example, how partner features are implemented in standalone modules in https://github.com/OCA/partner-contact

**Comment by marcelsavegnago** [comment]
> Hello @marcelsavegnago !
> 
> I don't think these features should be in a `base_` module, as the real "base" here is the core `fleet` module.
> 
> You should probably isolate these features into separate modules, each implementing one or some of them. You can check, for example, how partner features are implemented in standalone modules in https://github.com/OCA/partner-contact

I agree that the best way is to propose each feature in a different module. However, in the case of resources such as pivot, graph or other type of view it does not work very well because each module overwrites the available views.

https://github.com/Escodoo/fleet/blob/fcfc066487d016b3fed9d66f591138e3cb9ed193/base_fleet/views/fleet_vehicle.xml#L71

In the case of including the notebook tag in the vehicle form, what do you suggest? I am concerned with implementing a notebook for some module such as fleet_vehicle_agreement and end up conflicting with other modules that end up implementing the notebook tag as well.

Now, new fields and other things can be implemented each by a module.

**Comment by ivantodorovich** [comment]
> I agree that the best way is to propose each feature in a different module. However, in the case of resources such as pivot, graph or other type of view it does not work very well because each module overwrites the available views.

I'm not sure I understand the issue here. 
What other module is overwriting these values?

You can probably add the pivot and graph views in the same module, as they're related (for reports).
Maybe you can call it `fleet_vehicle_report`  or simply `fleet_vehicle_pivot` ?

> In the case of including the notebook tag in the vehicle form, what do you suggest? I am concerned with implementing a notebook for some module such as fleet_vehicle_agreement and end up conflicting with other modules that end up implementing the notebook tag as well.

Hmmm creating a `fleet_vehicle_notebook` module that introduces no new fields, maybe. Only adds the notebook to the form.
Other modules can depend on it to add fields or pages to the notebook.

Check this module for inspiration: https://github.com/OCA/partner-contact/tree/13.0/partner_contact_personal_information_page --> it's adding a new notebook page, but it's a similar idea

**Comment by marcelsavegnago** [comment]
@ivantodorovich 

* #52 - add field fuel_capacity
* #53 - add field calendar year
* #54 - add additional fuel types
* #55 - add notebook 
* #56 - add pivot and graph view

**Comment by marcelsavegnago** [comment]
> I'm not sure I understand the issue here.
> What other module is overwriting these values?

Yes, if I create a module to add only the pivot view and another to create add only the graphical view, one will overwrite the record **fleet.fleet_vehicle_action** created by the other if done as mentioned below:

**fleet_vehicle_pivot**
```
    <record id="fleet.fleet_vehicle_action" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,**pivot**,activity,form</field>
    </record>
```

**fleet_vehicle_graph**
```
    <record id="fleet.fleet_vehicle_action" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,**graph**,activity,form</field>
    </record>
```

The alternative would be to implement in both modules the following as mentioned below:
```
    <record id="fleet.fleet_vehicle_action" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,**pivot**,**graph**,activity,form</field>
    </record>
```

If someone implements a module that adds the calendar view, they will overwrite it too.
```
    <record id="fleet.fleet_vehicle_action" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,**calendar**,activity,form</field>
    </record>
```

I can create a single module by adding the pivot table and the graph view. Do you have a suggested name for the module if you think it is the most suitable option? 😄

* fleet_vehicle_additional_view
* fleet_vehicle_pivot_graph 
* fleet_vehicle_view_extension
* fleet_usability (generic name)
* fleet_vehicle_usability (generic name)
* fleet_vehicle_report (as suggested by you) (I don't know if it would be the most suitable name but that's fine by me)

The calendar view can also be created, but it lacks a relevant date to use since the vehicle data model has only the vehicle acquisition date and it does not seem valid to implement the calendar view.

Anyway, it is a small problem, but a little boring to deal with in my opinion.

**Pull request closed without merging**
