### PR TITLE
[14.0][IMP] add sequential and handle widget to inspection

### PR DESCRIPTION
**Pull request by rpsjr**
making inspection itens/lines easyer to handle

### CODE REVIEW

**Comment by rpsjr** [comment]
ezgif com-animated-gif-maker

**Review by rvalyi — APPROVED** [review]
LGTM (the re-order widget is only available when the inspection is in draft state if ever you wonder how to test it).

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
