### PR TITLE
[12.0][ADD] fleet_vehicle_model_compatible_product

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This module extends the fleet management functionality. Allows you to define which products are compatible with the vehicle model.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@mymage I refactored PR #48 

I closed PR # 44 and # 47 and put a specific flag to define if the product is part of the vehicle or not

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich @mamcode

**Review by mymage — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
