### PR TITLE
[14.0][ADD] fleet_vehicle_log_fuel

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
The Fuel Log model was deleted from odoo in v14. Thus, this module adds it again.

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@MiquelRForgeFlow Do you think it's worth increasing the test coverage?

**Comment by MiquelRForgeFlow** [comment]
> Do you think it's worth increasing the test coverage?

No, you can easily test it on runboat. Basically I am adding simply a new model, not adding complicated things on existing models.

**Comment by MiquelRForgeFlow** [comment]
Added Spanish translations.

**Review by MiquelRForgeFlow — COMMENTED** [review]
:+1:

**Review by ivantodorovich — APPROVED** [review]

**Comment by mariadforgeflow** [comment]
@ivantodorovich could you try to merge again please?

**Pull request merged**
